name: KICS
 
on:
  workflow_dispatch:
 
jobs:
  kics:
    name: Scan
    runs-on: ubuntu-latest
    # Skip any PR created by dependabot to avoid permissioning issues
    if: (github.actor != 'dependabot[bot]')
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Scan Iac with kics
    - name: run kics Scan
      uses: checkmarx/kics-action@v1.2
      with:
        path: '.'
        output_formats: 'sarif'
        output_path: results-dir
    # Always upload an artifact of everything in the results-dir
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: KICS report
        path: |
          results-dir
    - name: Upload SARIF file
      if: github.ref == 'refs/heads/master' && ${{ always() }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results-dir/results.sarif

